### PR TITLE
Improved typings

### PR DESCRIPTION
**Pull request by codeandcats**
Love the library ❤️

I'm trying to use it within my TS application but the existing typings cause my project to error as I have noImplicitAny enabled. I don't want to disable it just to use this library so I'd greatly appreciate if you could accept this pull request and republish your library to npm. 🙏 

Thanks in advance. 😄

### CODE REVIEW

**Comment by asvetliakov** [comment]
Thank you for your contribution! I'll push new version to npm soon
I probably rewrite this lib when i'll have some free time

**Comment by asvetliakov** [comment]
Published 1.4

**Comment by codeandcats** [comment]
Hi @asvetliakov,

Thanks for responding so quickly.

Is there a build step you normally run before publishing to npm that might have been missed, as I seem to be getting this error when trying to run my app with the latest version of huject...

```
Error: Cannot find module './container'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/huject/src/index.js:2:19)
```

**Comment by codeandcats** [comment]
Also, that's exciting to hear that you're thinking about rewriting the library. If you do, can I suggest a small modification to the method for resolving a class? In fact, you could probably modify the existing library as it is now to easily get this cool feature...

In my app I implemented a very thin wrapper around a huject container, just for my personal use mostly to get some slightly improved typing from it.

```
interface ConstructorWithoutParams<T> {
    new (): T;
}

interface ConstructorWithParams<T> {
    new (...params: any[]): T;
}

type Constructor<T> = ConstructorWithParams<T> | ConstructorWithoutParams<T>;

export class Container {
    private readonly container = new huject.Container();

    resolve<T>(type: Constructor<T>): T;
    resolve(name: string): any;

    resolve<T>(typeOrName: Constructor<T> | string): T | any {
        return this.container.resolve(typeOrName as any);
    }
}
```

The cool thing about this is if you write `const cat = container.resolve<Cat>();` the variable `cat` will be typed as a `Cat` at design-time, rather than an `any`.

**Comment by asvetliakov** [comment]
@codeandcats Try version 1.4.1 . I forgot to add npmignore to negate gitignore excluding.

Regarding your example to get the type of class from ```resolve()``` - last time i had tried something like it it had some issues with compiler. Many things in TS were changed since that, so it may work now.

**Pull request merged**
